name: Onewaysync

on:
  schedule:
    - cron: "0 2 * * 0"  # every Sunday at 2 AM UTC
  workflow_dispatch:      # manual trigger

jobs:
  update-layers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq sha256sum

      - name: Download all ArcGIS layers to temp folder
        run: |
          mkdir -p layers temp_layers
          BASE_URL="https://gisapps.nsdi.gov.lk/server/rest/services/Srilanka/All_Layers/MapServer"

          # Get list of all layers with id, name, type
          LAYERS=$(curl -s "${BASE_URL}?f=json" | jq -r '.layers[] | "\(.id) \(.name) \(.type)"')

          while read -r ID NAME TYPE; do
            FILE_NAME=$(echo "$NAME" | tr ' ' '_')
            echo "Processing layer $ID - $NAME ($TYPE)..."

            case $TYPE in
              Feature\ Layer)
                curl -s "${BASE_URL}/${ID}/query?where=1=1&outFields=*&f=geojson" -o "temp_layers/${FILE_NAME}.geojson"
                ;;
              Raster\ Layer)
                curl -s "${BASE_URL}/${ID}/export?f=image&format=png" -o "temp_layers/${FILE_NAME}.png"
                ;;
              *)
                curl -s "${BASE_URL}/${ID}/query?where=1=1&outFields=*&f=esriJSON" -o "temp_layers/${FILE_NAME}.json"
                ;;
            esac
          done <<< "$LAYERS"

      - name: Compare temp layers with existing layers
        id: checksum
        run: |
          mkdir -p .checksums
          CHANGED=false

          for TEMP_FILE in temp_layers/*; do
            BASENAME=$(basename "$TEMP_FILE")
            TARGET_FILE="layers/$BASENAME"

            if [ -f "$TARGET_FILE" ]; then
              if ! cmp -s "$TEMP_FILE" "$TARGET_FILE"; then
                echo "$BASENAME has changed."
                cp "$TEMP_FILE" "$TARGET_FILE"
                CHANGED=true
              fi
            else
              echo "$BASENAME is new."
              cp "$TEMP_FILE" "$TARGET_FILE"
              CHANGED=true
            fi
          done

          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

      - name: Commit & Push
        if: steps.checksum.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add layers/
          git commit -m "Update ArcGIS layers [skip ci]"
          git push
