name: Onewaysync

on:
  schedule:
    - cron: "0 2 * * 0"  # every Sunday at 2 AM UTC
  workflow_dispatch:      # allow manual trigger

jobs:
  update-layers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq sha256sum

      - name: Download all ArcGIS layers
        run: |
          mkdir -p layers
          BASE_URL="https://gisapps.nsdi.gov.lk/server/rest/services/Srilanka/All_Layers/MapServer"

          # Get list of layer IDs and names
          LAYERS=$(curl -s "${BASE_URL}?f=json" | jq -r '.layers[] | "\(.id) \(.name)"')

          while read -r ID NAME; do
            FILE_NAME=$(echo "$NAME" | tr ' ' '_').geojson
            echo "Downloading $NAME..."
            curl -s "${BASE_URL}/${ID}/query?where=1=1&outFields=*&f=geojson" -o "layers/$FILE_NAME"
          done <<< "$LAYERS"

      - name: Generate checksums
        run: |
          mkdir -p .checksums
          sha256sum layers/*.geojson > .checksums/new_sums.txt

      - name: Compare checksums
        id: checksum
        run: |
          if [ -f .checksums/old_sums.txt ]; then
            if cmp -s .checksums/new_sums.txt .checksums/old_sums.txt; then
              echo "No changes detected."
              echo "changed=false" >> $GITHUB_OUTPUT
              exit 0
            fi
          fi
          echo "Changes detected."
          echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit & Push
        if: steps.checksum.outputs.changed == 'true'
        run: |
          cp .checksums/new_sums.txt .checksums/old_sums.txt
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add layers/ .checksums/old_sums.txt
          git commit -m "Update ArcGIS layers [skip ci]"
          git push
